### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by kgorgolewski** [jackrosenthal/python-cgi#3]
hi,
how can i use legacy-cgi? while trying something like `import legacy_cgi` or `from legacy_cgi import cgi` i am getting an error that the module cannot be found, although installed via `pip install legacy-cgi`.
any hint would be appreciated.
thanks
krzysztof

**Comment by jackrosenthal** [comment]
The modules were not renamed, so code that was written for Python 3.12 and earlier should work without any modifications on Python 3.13+ with this package installed.

**Comment by kgorgolewski** [comment]
hmm thanks jack for your quick response. hope for the best🤞
