### ISSUE TITLE
Please make a new release (with tests)

### ISSUE THREAD

**Issue by mgorny** [jackrosenthal/python-cgi#4]
Could you please make a new release that includes tests (and ideally has them in sdist too)? The current release was cut just before tests were added. We'd really use a stable archive with tests available to package this in Gentoo.

**Comment by hroncok** [comment]
We'd appreciate this in Fedora as well.

**Comment by jackrosenthal** [comment]
https://pypi.org/project/legacy-cgi/2.6.1/ (and it has tests in sdist :heavy_check_mark:)

**Comment by mgorny** [comment]
Thanks a lot!
